export const DEFAULT_LOG_LIMIT = 50;
export const DEFAULT_REQUEST_LIMIT = 50;

export const COMMAND_TIMEOUT = 600000;

export const SCREENSHOT_QUALITY = 80;
export const INPUT_SUBMIT_DELAY = 150;

export const MAX_LOGS_PER_TAB = 1000;
export const MAX_REQUESTS_PER_TAB = 500;
export const MAX_HISTORY_ITEMS = 100;

export const FILE_PERMISSIONS_EXECUTABLE = 0o755;

export const SCREENSHOT_COMMAND_TIMEOUT = 600000;
export const DEFAULT_COMMAND_TIMEOUT = 10000;
