name: 'Callable CI'

on:
  workflow_call:
    inputs:
      run_lint:
        description: 'Run lint checks'
        type: boolean
        required: true
      run_build:
        description: 'Run build'
        type: boolean
        required: true
    secrets:
      TURBO_TOKEN:
        description: Turbo token for cache
        required: false
      TURBO_TEAM:
        description: Turbo team for cache
        required: false

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  lint:
    if: inputs.run_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install

      - name: Run lint
        run: pnpm run lint

  build:
    if: inputs.run_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Build package
        run: pnpm run build

