name: "Main Branch & Release"

on:
  push:
    branches:
      - main
    tags:
      - "v*" # e.g.: v1.0.0

permissions:
  pull-requests: write
  contents: write
  id-token: write

concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_to_main_ci:
    name: "Main CI"
    uses: ./.github/workflows/callable-ci.yml
    with:
      run_lint: true
      run_build: true
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

  release:
    name: "Release Package"
    needs: [push_to_main_ci]
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run publish:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Package Release Assets
        if: steps.changesets.outputs.published == 'true'
        run: |
          VERSION=${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}

          # Package CLI (create tarball from npm package)
          cd packages/cli
          npm pack
          mv chrome-cmd-${VERSION}.tgz ../../chrome-cmd-v${VERSION}.tgz
          cd ../..

          # Build Chrome Extension
          cd packages/chrome-extension
          pnpm install
          pnpm build
          cd dist
          zip -r ../../../chrome-extension-v${VERSION}.zip . -x "*.DS_Store"
          cd ../../..

          echo "✅ Packaged CLI and extension v${VERSION}"

      - name: Upload Release Assets
        if: steps.changesets.outputs.published == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          files: |
            chrome-cmd-v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}.tgz
            chrome-extension-v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}.zip
          body: |
            ## Installation

            ### CLI
            ```bash
            # Install
            npm install -g chrome-cmd

            # Update (if already installed)
            chrome-cmd update
            ```

            ### Chrome Extension
            1. Download `chrome-extension-v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}.zip`
            2. Extract to a permanent location
            3. Load in Chrome at `chrome://extensions/` (Developer mode → Load unpacked)
            4. Copy Extension ID and run: `chrome-cmd host install`

            ## Documentation

            See the [README](https://github.com/lucasvtiradentes/chrome-cmd#readme) for complete documentation.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
